version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
  
  php:
    image: php:8.2-fpm-alpine
    volumes:
      - ./html:/var/www/html
  
  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  backend1:
    image: node:18-alpine
    ports:
      - "3000:3000"
    command: sh -c "echo 'Backend is running' && sleep 3600"

volumes:
  db_data:
